export const LISTAR_PELICULAS_POPULAR = "LISTAR_PELICULAS_POPULAR";

export const LISTAR_SERIES_POPULAR = "LISTAR_SERIES_POPULAR";

export const LISTAR_MOVIES_MULTI = "LISTAR_MOVIES_MULTI";

export const LISTAR_DETALLES_MOVIE = "LISTAR_DETALLES_MOVIE";

export const LISTAR_REPARTO_MOVIE = "LISTAR_REPARTO_MOVIE";

export const LISTAR_REPARTO_SERIE = "LISTAR_REPARTO_SERIE";

export const LISTAR_DETALLES_SERIE = "LISTAR_DETALLES_SERIE";